-----------------------------------------------------------------------------
-- OPTIONS
-----------------------------------------------------------------------------

vim.opt.background = "dark"
vim.opt.mouse = "a"
vim.opt.encoding = "utf-8"
vim.opt.termguicolors = true -- true colors in terminal
vim.opt.inccommand = "nosplit" -- show ex-command change previews
vim.opt.timeoutlen = 500 -- lower timeout for mappings
vim.opt.ttimeoutlen = 10 -- fix esc in tmux
vim.opt.clipboard = "unnamedplus" -- use system clipboard for regular yank/paste
vim.opt.expandtab = true -- expand tabs to spaces
vim.opt.smarttab = false -- fuck tabs
vim.opt.mat = 5 -- duration to show matching brace
vim.opt.autoread = true -- reload files automatically
vim.opt.number = true -- draw line numbers
vim.opt.relativenumber = true -- draw relative line numbers
vim.opt.swapfile = false -- disable swap files
vim.opt.spell = false -- no spell checking
vim.opt.undolevels = 150 -- only undo up to 150 times
vim.opt.lazyredraw = true -- don't redraw screen during macros
vim.opt.sc = true -- show incomplete command at bottom right
vim.opt.ignorecase = true -- only be case sensitive when search contains uppercase
vim.opt.smartcase = true -- only be case sensitive when search contains uppercase
vim.opt.splitbelow = true -- open new split windows below current
vim.opt.hidden = true -- allow hidden buffers
vim.opt.report = 0 -- always report when lines are changed
vim.opt.visualbell = true -- don't beep
vim.opt.foldenable = false -- no autofold
vim.opt.foldmethod = "syntax"
vim.opt.foldlevel = 1
vim.opt.foldnestmax = 10
vim.opt.tabstop = 8 -- a n-space tab width
vim.opt.shiftwidth = 2 -- allows the use of < and > for VISUAL indenting
vim.opt.softtabstop = 2 -- counts n spaces when DELETE or BACKSPACE is used
vim.opt.textwidth = 78
vim.opt.autoindent = true -- auto indents next new line
vim.opt.smartindent = true -- intelligent indenting
vim.opt.hlsearch = false -- don't highlight search results
vim.opt.incsearch =  true -- increment search
vim.opt.backspace = "indent,eol,start"
vim.opt.history = 1000 -- 1000 lines of command history
vim.opt.cmdheight = 1 -- command line height
vim.opt.ruler = true -- ruler display in statusline
vim.opt.showmode = true -- show mode at bottom of screen
vim.opt.backup = false -- don't keep backups after close
vim.opt.writebackup = true -- do keep one while working
vim.opt.backupdir = os.getenv("HOME") .. "/.vim/backup/,/tmp"
vim.opt.backupcopy = "yes"
vim.opt.directory = os.getenv("HOME") .. "/.vim/backup/,/tmp"
vim.opt.showmatch = true -- show matching brackets (), {}, []
vim.opt.whichwrap = "h,l,<,>,[,]"
vim.opt.showcmd = true
vim.opt.modeline = true
vim.opt.formatoptions = "tcqjl"
vim.opt.selection = "inclusive"
vim.opt.autowrite = true
vim.opt.cinoptions = "g0,:0,l1,(0,t0"
vim.opt.shortmess = "at" -- disable intro screen
vim.opt.complete = ".,t,i,b,w,k"
vim.opt.wildchar = ('\t'):byte()
vim.opt.wildmenu = true
vim.opt.wildmode = "longest:full,full"
vim.opt.wildignore = "*/.git/*,*/tmp/*,*.swp,*/node_modules/*"
vim.opt.previewheight = 5
vim.opt.joinspaces = true
vim.opt.magic = true
vim.opt.suffixes = ".bak,~,.o,.info,.log,.rbx,.swp"
vim.opt.title = true
vim.opt.scrolloff = 8 -- start scrolling at 8 lines away from margins
vim.opt.sidescrolloff = 15
vim.opt.sidescroll = 1
vim.opt.cursorline = true
vim.opt.omnifunc = "syntaxcomplete#Complete"
vim.opt.laststatus = 2 -- always show statusline
vim.opt.completeopt = "menu,menuone,noselect"
vim.opt.listchars:append({ trail = "·", precedes = "«", extends = "»", eol = "↲", tab = "▸\\ " })
